from ansible_mikrotik_utils import MikrotikConfig

def test_compare():
    BASE = """
    /ip address
    add address=192.168.88.1/24
    add address=10.0.0.1 network=10.0.0.2

    /ip firewall filter
    add chain=test comment="1"
    add chain=test comment="2"
    add chain=test comment="3"
    add chain=test comment="A"
    add chain=test comment="B"
    add chain=test comment="C"
    add chain=test comment="D"
    add chain=test comment="E"
    add chain=test comment="4"
    add chain=test comment="5"
    add chain=test comment="6"

    /interface bridge
    set 0 wat

    """

    TARGET = """
    /ip address
    add address=192.168.88.1/24
    add address=10.0.0.1 network=10.0.0.2

    /ip firewall filter
    add chain=test comment="foo"
    add chain=test comment="C"
    add chain=test comment="D"
    add chain=test comment="A"
    add chain=test comment="E"
    add chain=test comment="B"
    add chain=test comment="bar"

    /interface bridge
    set 0 wat

    """

    CHANGES = """
    # Generated by: ansible-mikrotik-utils 0.1 for ROS None
    /ip firewall filter

    remove 0
    remove 0
    remove 0
    remove 5
    remove 5
    remove 5
    add chain=test comment=foo place-before=1
    add chain=test comment=bar
    move 1 4
    move 2 2
    move 1 6
    move 2 4
    """
    base, target = map(MikrotikConfig.parse, (BASE, TARGET))
    actual_changes = str(base.difference(target)).strip()
    expected_changes = '\n'.join(map(str.strip, CHANGES.strip().split('\n')))
    assert actual_changes == expected_changes
